version: '3'

services:
  frontend:
    build: ./client

    # Если указать это, то это будет передано во флаг -p, тогда контейнер будет доступен извне.
    # Dockerfile у клиента говорит, что контейнер слушает изнутри докура по порту 8080 (EXPOSE 8080)
    # Другие контейнеры могут обращаться к нему (что и делает nginx сервис)
    # ports:
    # - "8080:8080"
    
    # Пока не разобрался, зачем это
    # volumes:
    #   - ./client/public:/app/public

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: database
      PGHOST: db
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
