name: CI/CD Pipeline

on:
  push:
    branches:
      - main 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PFSN_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build backend Docker image
      run: docker build -t backend ./backend

    - name: Build frontend Docker image
      run: docker build -t frontend ./client

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push backend Docker image
      run: docker push backend

    - name: Push frontend Docker image
      run: docker push frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa  user@your_vps_ip << 'EOF'
          docker pull backend
          docker pull frontend
          cd ./pfsn
          docker-compose down
          docker-compose up -d
        EOF